<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="box_length" value="0.1" />
    <xacro:property name="second_link_height" value="0.2" />
    <xacro:property name="second_link_radius" value="0.1" />
    <xacro:property name="wheel_mass" value="1.0" />
    <xacro:property name="caster_wheel_mass" value="0.5" />
    <xacro:property name="box_mass" value="5.0" />
     
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="${box_mass}" l="${base_length}" w="${base_width}" h="${base_height}" 
                           xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="gray"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" l="${wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz="0 0 ${-wheel_radius/2.0}" rpy="0 0 0"/>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz="0 0 ${-wheel_radius/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="${caster_wheel_mass}" r="${wheel_radius/2.0}" xyz="0 0 ${-wheel_radius/2.0}" rpy="0 0 0"/>
    </link>

    <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="${second_link_radius}" length="${second_link_height}"/>
            </geometry>
            <origin xyz="0 0 ${second_link_height/2.0}" rpy="0 0 0"/>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${second_link_radius}" length="${second_link_height}"/>
            </geometry>
            <origin xyz="0 0 ${second_link_height/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${second_link_radius}" l="${second_link_height}" 
                                xyz="0 0 ${second_link_height/2.0}" rpy="0 0 0"/>
    </link>

    <link name="third_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_length} ${box_length}" />
            </geometry>
            <origin xyz="0 0 ${box_length/2.0}" rpy="0 0 0" />
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_length} ${box_length}" />
            </geometry>
            <origin xyz="0 0 ${box_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.1" l="${box_length}" w="${box_length}" h="${box_length}" 
                           xyz="0 0 ${box_length/2.0}" rpy="0 0 0"/>
    </link>

    <link name="base_footprint_link">
        
    </link>

    <joint name="base_to_footprint_link_joint" type="fixed">
        <parent link="base_footprint_link"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        
        
    </joint>
    <joint name="base_second_link_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="second_link"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="1 0 0" />
        <limit lower="-0.18" upper="0.18" velocity="100" effort="100"/>
    </joint>

    <joint name="second_to_third_link_joint" type="revolute">
        <parent link="second_link"/>
        <child link="third_link"/>
        <origin xyz="0 0 ${second_link_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
    </joint>

    <joint name="base_to_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(-base_width-wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    <joint name="base_to_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width+wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    <joint name="base_to_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/3.0} 0 0" rpy="0 0 0"/>
        
    </joint>


</robot>