<?xml version="1.0"?>
<robot name="cagopa_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro"/>
    <xacro:include filename="mobile_base.xacro"/>
    <xacro:include filename="mobile_base_gazebo.xacro"/>
    --<xacro:include filename="camera.xacro"/> 
    <xacro:include filename="arm_properties.xacro"/>
    <xacro:include filename="arm.xacro"/>


    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${(base_length/2.0)-(0.1/2.0)} 0 ${base_height}" rpy="0 0 0"/>
        
    </joint>
</robot>